USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SPOTIFY_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW VW_SONG_CATALOG
COMMENT = 'One row per unique song observed by the pipeline; not current playlist membership'
AS
SELECT
    S.SONG_ID,
    S.NAME AS SONG_NAME,
    S.DURATION_MS,
    ROUND(S.DURATION_MS / 1000.0, 1) AS DURATION_SECONDS,
    S.EXPLICIT,
    S.TRACK_NUMBER,
    S.ADDED_AT,
    TO_DATE(S.ADDED_AT) AS ADDED_DATE,

    A.ALBUM_ID,
    A.NAME AS ALBUM_NAME,
    A.RELEASE_DATE AS RELEASE_DATE_RAW,
    TRY_TO_NUMBER(LEFT(A.RELEASE_DATE, 4)) AS RELEASE_YEAR,
    A.TOTAL_TRACKS AS ALBUM_TOTAL_TRACKS,

    LISTAGG(DISTINCT AR.NAME, ', ')
        WITHIN GROUP (ORDER BY AR.NAME) AS ARTIST_NAMES,

    COUNT(DISTINCT AR.ARTIST_ID) AS ARTIST_COUNT

FROM SPOTIFY_DB.RAW.SONGS AS S

LEFT JOIN SPOTIFY_DB.RAW.ALBUMS AS A
    ON S.ALBUM_ID = A.ALBUM_ID

LEFT JOIN SPOTIFY_DB.RAW.SONG_ARTISTS AS SA
    ON S.SONG_ID = SA.SONG_ID

LEFT JOIN SPOTIFY_DB.RAW.ARTISTS AS AR
    ON SA.ARTIST_ID = AR.ARTIST_ID

GROUP BY
    S.SONG_ID,
    S.NAME,
    S.DURATION_MS,
    S.EXPLICIT,
    S.TRACK_NUMBER,
    S.ADDED_AT,
    A.ALBUM_ID,
    A.NAME,
    A.RELEASE_DATE,
    A.TOTAL_TRACKS;

    ----------------------------
    SELECT
    COUNT(*) AS VIEW_ROWS,
    COUNT(DISTINCT SONG_ID) AS UNIQUE_SONGS,
    COUNT_IF(ARTIST_COUNT = 0) AS SONGS_WITHOUT_ARTISTS,
    COUNT_IF(ALBUM_ID IS NULL) AS SONGS_WITHOUT_ALBUMS
FROM SPOTIFY_DB.ANALYTICS.VW_SONG_CATALOG;
---------------------------------------------------
CREATE OR REPLACE VIEW SPOTIFY_DB.ANALYTICS.VW_ARTIST_SUMMARY
COMMENT = 'One row per artist with catalog-level song metrics'
AS
SELECT
    AR.ARTIST_ID,
    AR.NAME AS ARTIST_NAME,

    COUNT(DISTINCT S.SONG_ID) AS SONG_COUNT,
    COUNT(DISTINCT S.ALBUM_ID) AS ALBUM_COUNT,

    ROUND(AVG(S.DURATION_MS) / 1000.0, 1)
        AS AVG_SONG_DURATION_SECONDS,

    COUNT_IF(S.EXPLICIT = TRUE)
        AS EXPLICIT_SONG_COUNT,

    ROUND(
        100.0 * COUNT_IF(S.EXPLICIT = TRUE)
        / NULLIF(COUNT(DISTINCT S.SONG_ID), 0),
        1
    ) AS EXPLICIT_SONG_PERCENTAGE,

    MIN(S.ADDED_AT) AS FIRST_SONG_ADDED_AT,
    MAX(S.ADDED_AT) AS LATEST_SONG_ADDED_AT

FROM SPOTIFY_DB.RAW.ARTISTS AS AR

JOIN SPOTIFY_DB.RAW.SONG_ARTISTS AS SA
    ON AR.ARTIST_ID = SA.ARTIST_ID

JOIN SPOTIFY_DB.RAW.SONGS AS S
    ON SA.SONG_ID = S.SONG_ID

GROUP BY
    AR.ARTIST_ID,
    AR.NAME;
    --------------------------------------------
    SELECT
    COUNT(*) AS VIEW_ROWS,
    COUNT(DISTINCT ARTIST_ID) AS UNIQUE_ARTISTS,
    SUM(SONG_COUNT) AS TOTAL_ARTIST_SONG_RELATIONSHIPS,
    COUNT_IF(SONG_COUNT = 0) AS ARTISTS_WITHOUT_SONGS
FROM SPOTIFY_DB.ANALYTICS.VW_ARTIST_SUMMARY;
----------------------------
SELECT
    ARTIST_NAME,
    SONG_COUNT,
    ALBUM_COUNT
FROM SPOTIFY_DB.ANALYTICS.VW_ARTIST_SUMMARY
ORDER BY SONG_COUNT DESC, ARTIST_NAME
LIMIT 10;
------------------------------
SELECT
    COUNT(*) AS VIEW_ROWS,
    COUNT(DISTINCT ARTIST_ID) AS UNIQUE_ARTISTS,
    SUM(SONG_COUNT) AS TOTAL_ARTIST_SONG_RELATIONSHIPS,
    COUNT_IF(SONG_COUNT = 0) AS ARTISTS_WITHOUT_SONGS
FROM SPOTIFY_DB.ANALYTICS.VW_ARTIST_SUMMARY;

SELECT COUNT(*)
FROM SPOTIFY_DB.ANALYTICS.VW_SONG_CATALOG;
-----------------------------------------------------------------------------------------------BQ

-- Compute isolation
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS BQ_SYNC_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for publishing curated Snowflake analytics to BigQuery';


-- Create the service role and non-human user
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS BQ_SYNC_ROLE
    COMMENT = 'Read-only role for the Snowflake to BigQuery publication job';

CREATE USER IF NOT EXISTS BQ_SYNC_USER
    TYPE = SERVICE
    DEFAULT_ROLE = BQ_SYNC_ROLE
    DEFAULT_WAREHOUSE = BQ_SYNC_WH
    DEFAULT_NAMESPACE = 'SPOTIFY_DB.ANALYTICS'
    COMMENT = 'Cloud Run service user for BigQuery analytics publication';


-- Connect the role hierarchy and grant minimum access
USE ROLE SECURITYADMIN;

GRANT ROLE BQ_SYNC_ROLE TO USER BQ_SYNC_USER;
GRANT ROLE BQ_SYNC_ROLE TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE BQ_SYNC_WH
    TO ROLE BQ_SYNC_ROLE;

GRANT USAGE ON DATABASE SPOTIFY_DB
    TO ROLE BQ_SYNC_ROLE;

GRANT USAGE ON SCHEMA SPOTIFY_DB.ANALYTICS
    TO ROLE BQ_SYNC_ROLE;

GRANT SELECT ON VIEW SPOTIFY_DB.ANALYTICS.VW_SONG_CATALOG
    TO ROLE BQ_SYNC_ROLE;

GRANT SELECT ON VIEW SPOTIFY_DB.ANALYTICS.VW_ARTIST_SUMMARY
    TO ROLE BQ_SYNC_ROLE;

SHOW GRANTS TO ROLE BQ_SYNC_ROLE;    
SHOW GRANTS TO USER BQ_SYNC_USER;
SHOW USERS LIKE 'BQ_SYNC_USER';

USE ROLE SECURITYADMIN;

GRANT ROLE BQ_SYNC_ROLE
TO USER BQ_SYNC_USER;

SHOW GRANTS TO USER BQ_SYNC_USER;

USE ROLE BQ_SYNC_ROLE;
USE WAREHOUSE BQ_SYNC_WH;

SELECT
    'VW_SONG_CATALOG' AS VIEW_NAME,
    COUNT(*) AS ROW_COUNT
FROM SPOTIFY_DB.ANALYTICS.VW_SONG_CATALOG

UNION ALL

SELECT
    'VW_ARTIST_SUMMARY',
    COUNT(*)
FROM SPOTIFY_DB.ANALYTICS.VW_ARTIST_SUMMARY;

USE ROLE USERADMIN;

ALTER USER BQ_SYNC_USER
SET RSA_PUBLIC_KEY ='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2BgSrGnvhZ5p4s4I9XLPpgiTZzkhTzWDMvsDP8znmKir2uv/Dx3H0m3aslfdNSztwv11x6Gp/XvIYfqQh+XckDfxxQOH8iPowqvV+ku9LXjTQBahoueDNDlUBfNBOPGRTL3FLm2ll3FBbGk2qp1Ha/eQaGiitw9+NLhHiMOSIHkXE5nFPMxCkvQ4z3/YI+bYPhLpRISWt9CFPxm0WLlU53BZ9owsBLWMUzSkohguFf6TSrXOQh2yF/Wo+UeyMiwnrU0zySdm9ag76EFzDDrdLm6uEDB/MXESxvOl4STE/c8vrr0RUdYioYdmhHYeVo/Al1RfA0d+rnYWzk1LFs3VPQIDAQAB';

SHOW USERS LIKE 'BQ_SYNC_USER';

USE ROLE SECURITYADMIN;

GRANT USAGE ON SCHEMA SPOTIFY_DB.RAW
TO ROLE BQ_SYNC_ROLE;

SHOW GRANTS TO ROLE BQ_SYNC_ROLE;

USE ROLE ACCOUNTADMIN;

SHOW GRANTS ON VIEW
SPOTIFY_DB.ANALYTICS.VW_SONG_CATALOG;

SHOW GRANTS TO ROLE SYSADMIN;

SELECT
    "privilege",
    "granted_on",
    "name"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" IN (
    'SPOTIFY_DB',
    'SPOTIFY_DB.RAW',
    'SPOTIFY_DB.RAW.SONGS',
    'SPOTIFY_DB.RAW.ALBUMS',
    'SPOTIFY_DB.RAW.ARTISTS',
    'SPOTIFY_DB.RAW.SONG_ARTISTS'
)
ORDER BY "name", "privilege";

----------------------------------------------------------------
USE ROLE SECURITYADMIN;

GRANT USAGE ON SCHEMA SPOTIFY_DB.RAW
TO ROLE SYSADMIN;

GRANT SELECT ON TABLE SPOTIFY_DB.RAW.SONGS
TO ROLE SYSADMIN;

GRANT SELECT ON TABLE SPOTIFY_DB.RAW.ALBUMS
TO ROLE SYSADMIN;

GRANT SELECT ON TABLE SPOTIFY_DB.RAW.ARTISTS
TO ROLE SYSADMIN;

GRANT SELECT ON TABLE SPOTIFY_DB.RAW.SONG_ARTISTS
TO ROLE SYSADMIN;
---------------------------------------
REVOKE USAGE ON SCHEMA SPOTIFY_DB.RAW
FROM ROLE BQ_SYNC_ROLE;


SHOW GRANTS TO ROLE SYSADMIN;


SELECT
    "privilege",
    "granted_on",
    "name"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" IN (
    'SPOTIFY_DB.RAW',
    'SPOTIFY_DB.RAW.SONGS',
    'SPOTIFY_DB.RAW.ALBUMS',
    'SPOTIFY_DB.RAW.ARTISTS',
    'SPOTIFY_DB.RAW.SONG_ARTISTS'
)
ORDER BY "name";

SHOW GRANTS TO ROLE BQ_SYNC_ROLE;
SELECT
    "privilege",
    "granted_on",
    "name"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" LIKE 'SPOTIFY_DB.RAW%'
ORDER BY "name";

SELECT GET_DDL(
    'VIEW',
    'SPOTIFY_DB.ANALYTICS.VW_SONG_CATALOG'
);

SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'ANALYTICS' 
  
